### ISSUE TITLE
5. Reportes

### ISSUE THREAD

**Issue by MichaelBordaPoli** [ISWPOLI/MMLI#12]
** Descripción **
Como gerente se requiere generar reportes de los tiempos utilizados.
- [ ] Se generará reporte de los tiempos utilizados en las tareas dependiendo de los criterios ingresados.
- [ ] se generara un reporte por área
- [ ] se generara un reporte por proyecto
