### ISSUE TITLE
0. Planeación fechas de entrega

### ISSUE THREAD

**Issue by MichaelBordaPoli** [ISWPOLI/MMLI#36]
**Descripción**

Planeación de fechas de entrega de iteraciones del producto.

- [x] historias de usuario que se entregaran en el primer corte
- [x] historias de usuario que se entregaran en el segundo corte
- [x] historias de usuario que se entregaran en el tercer corte
