### ISSUE TITLE
0.1 Presentación Proyecto

### ISSUE THREAD

**Issue by MichaelBordaPoli** [ISWPOLI/MMLI#37]
**Descripción**

- [x] Exposición modelo de negocio
- [x] Presentación historias de usuario en github
- [x] Presentación mockups de la aplicación

**Comment by MichaelBordaPoli** [comment]
Se realizo la presentación el día 6 de septiembre.
