### ISSUE TITLE
8. Documentación

### ISSUE THREAD

**Issue by MichaelBordaPoli** [ISWPOLI/MMLI#42]
**Descripción**

Se realizara la siguiente documentación del proyecto:
- [x] Documento de presentación del proyecto con: Introducción, Objetivos SMART, Marco teórico, Modelado del negocio (Canvas)   , Problema de investigación ,Justificación.
- [x] Documento de requerimientos
- [x] Documentos de casos de uso
- [x] Documento con diagramas de la aplicación.

**Comment by MichaelBordaPoli** [comment]
Se adjunta avance del proyecto de gestión de tiempos.

Esta documentación esta sujeta a cambios.

[MMLI Project.docx](https://github.com/ISWPOLI/MMLI/files/1330114/MMLI.Project.docx)

[formato-ieee-830- SIS-GT.docx](https://github.com/ISWPOLI/MMLI/files/1333597/formato-ieee-830-.SIS-GT.docx)
